import type { SendEmail } from '@cloudflare/workers-types';
/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=services/cloudflare-mail/wrangler.jsonc --include-runtime=false --strict-vars=false services/cloudflare-mail/worker-configuration.d.ts` (hash: d50bcc437c3c44d7de591af3f2a3cc54)
interface __BaseEnv_Env {
  EMAIL: SendEmail;
  DISPATCH_ENVIRONMENT: string;
  DISPATCH_ORIGIN: string;
  MAIL_FROM: string;
  MAIL_TOKEN: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./worker');
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv
    extends StringifyValues<
      Pick<Cloudflare.Env, 'DISPATCH_ENVIRONMENT' | 'DISPATCH_ORIGIN' | 'MAIL_FROM' | 'MAIL_TOKEN'>
    > {}
}

export type { Env };
