export const paycom = Object.freeze({
  id: 'paycom',
  name: 'Paycom',
  description: 'Employee rosters and timecards, collected into your DSP workspace.',
  actions: [
    'connection.save',
    'connection.verify',
    'connection.disable',
    'collection.run',
    'workforce.read',
  ],
  pages: ['employees', 'timecards', 'connections'],
  jobs: ['paycom.collect'],
  hosts: [
    'www.paycomonline.net',
    'time-and-attendance.paycomonline.net',
    'paycomonline.net',
    'www.paycom.com',
    'fonts.googleapis.com',
    'fonts.gstatic.com',
    'www.google.com',
    'www.gstatic.com',
    'www.recaptcha.net',
  ],
});
