'use strict';
const test = require('node:test'), assert = require('node:assert/strict');
const fs = require('node:fs'), os = require('node:os'), path = require('node:path'), { spawnSync } = require('node:child_process');
test('initial layout creates owned private catalogs and preserves configuration on retry', t => {
  if (process.geteuid() === 0 || spawnSync('/usr/bin/sudo', ['-n', '/usr/bin/true']).status !== 0) return t.skip('requires unprivileged account with sudo');
  const root = fs.mkdtempSync(path.join(os.homedir(), '.dispatch-install-layout-')); fs.chmodSync(root, 0o700);
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  const config = { uid: process.geteuid(), gid: process.getegid(), localRoot: path.join(root, 'local'), unitRoot: path.join(root, 'units') };
  const script = 'require(process.argv[1]).initializeLayout(JSON.parse(process.argv[2]))';
  const run = () => spawnSync('/usr/bin/sudo', ['-n', process.execPath, '-e', script, path.resolve(__dirname, "../src/install-layout.js"), JSON.stringify(config)], { encoding: 'utf8' });
  let result = run(); assert.equal(result.status, 0, result.stderr);
  const file = path.join(config.localRoot, 'config/platform-releases.json');
  assert.equal(fs.statSync(file).uid, config.uid); assert.equal(fs.statSync(file).mode & 0o777, 0o600);
  const value = { schemaVersion: 1, releases: { fixture: {} } }; fs.writeFileSync(file, JSON.stringify(value));
  const env = path.join(config.localRoot, 'config/provisioning.env'); fs.appendFileSync(env, 'FIXTURE=preserved\n');
  result = run(); assert.equal(result.status, 0, result.stderr);
  assert.deepEqual(JSON.parse(fs.readFileSync(file)), value); assert.match(fs.readFileSync(env, 'utf8'), /FIXTURE=preserved/);
  fs.unlinkSync(file); fs.symlinkSync('/etc/passwd', file);
  assert.notEqual(run().status, 0); fs.unlinkSync(file);
});
