const { test, expect } = require('@playwright/test');

async function login(page) {
  await page.goto('/');
  await page.getByLabel('Email address').fill('platform@example.test');
  await page.getByLabel('Password', { exact: true }).fill('synthetic preview password');
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'DSPs', exact: true })).toBeVisible();
}
const nav = page => page.locator('.desktop-sidebar').getByRole('navigation');

test('View opens the owner interface, survives refresh, isolates tabs and exits cleanly', async ({ page, context }) => {
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  page.on('console', m => { if (m.type() === 'error' && !m.text().includes('favicon')) errors.push(m.text()); });
  await login(page);
  await page.getByRole('button', { name: 'Northline Logistics NL01', exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'View', exact: true }).click();
  const banner = page.getByRole('region', { name: 'DSP viewing mode' });
  await expect(banner).toContainText('Viewing Northline Logistics as DSP owner');
  await expect(banner).toContainText('Full owner access. Changes are saved to this DSP.');
  await expect(page).toHaveTitle('Home Page · Dispatch');
  await expect(nav(page).getByRole('link')).toHaveText(['Home Page', 'Paycom', 'Team & Roles', 'Settings']);
  await page.goto('/#/onboarding');
  await expect(page).toHaveURL(/#\/dashboard$/);
  await expect(banner).toBeVisible();
  const otherTab = await context.newPage();
  await otherTab.goto('/');
  await expect(otherTab.getByRole('heading', { name: 'DSPs', exact: true })).toBeVisible();
  await expect(otherTab.getByRole('region', { name: 'DSP viewing mode' })).toHaveCount(0);
  await otherTab.close();
  await nav(page).getByRole('link', { name: 'Team & Roles', exact: true }).click();
  await expect(page.getByText('Alex Morgan', { exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Invite member', exact: true })).toBeEnabled();
  await page.getByRole('button', { name: 'Actions for Jamie Chen', exact: true }).click();
  await expect(page.getByRole('menuitem', { name: 'Change role', exact: true })).toBeEnabled();
  await expect(page.getByRole('menuitem', { name: 'Remove member', exact: true })).toBeEnabled();
  await page.keyboard.press('Escape');
  await page.getByRole('tab', { name: 'Roles', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Create role', exact: true })).toHaveCount(0);
  await expect(page.locator('.role-row h2')).toHaveText(['Owner', 'Manager', 'Dispatcher', 'Driver']);
  await expect(page.getByText('View permissions', { exact: true })).toHaveCount(0);
  await expect(page.getByText('organization · owner', { exact: true })).toHaveCount(0);
  await page.getByRole('tab', { name: 'Members', exact: true }).click();
  await page.getByRole('button', { name: 'Actions for Jamie Chen', exact: true }).click();
  await page.getByRole('menuitem', { name: 'Change role', exact: true }).click();
  await page.getByLabel('Role', { exact: true }).selectOption({ label: 'Dispatcher' });
  await page.getByRole('button', { name: 'Save role', exact: true }).click();
  await expect(page.getByRole('row').filter({ hasText: 'Jamie Chen' })).toContainText('Dispatcher');
  await expect(page.getByRole('tab', { name: 'Activity', exact: true })).toHaveCount(0);
  await nav(page).getByRole('link', { name: 'Settings', exact: true }).click();
  await page.getByRole('tab', { name: 'Audit log', exact: true }).click();
  await expect(page.getByRole('row').filter({ hasText: 'membership role update' }).first()).toContainText('platform@example.test');
  await expect(page.getByRole('cell', { name: 'organization view start', exact: true })).toHaveCount(0);
  await page.reload();
  await expect(page.getByRole('tab', { name: 'Audit log', exact: true })).toHaveAttribute('data-state', 'active');
  await nav(page).getByRole('link', { name: 'Team & Roles', exact: true }).click();
  await expect(banner).toBeVisible();
  await expect(page.getByText('Alex Morgan', { exact: true })).toBeVisible();
  await page.screenshot({ path: '/tmp/dispatch-dsp-view-desktop.png' });
  await nav(page).getByRole('link', { name: 'Settings', exact: true }).click();
  await expect(page.locator('main').getByText('Northline Logistics', { exact: true })).toBeVisible();
  await expect(page.locator('main').getByText('platform@example.test', { exact: true })).toBeVisible();
  await page.getByRole('tab', { name: 'Security', exact: true }).click();
  await expect(page.getByLabel('Current password', { exact: true })).toBeEnabled();
  await expect(page.getByRole('button', { name: 'Change password', exact: true })).toBeEnabled();
  await banner.getByRole('button', { name: 'Exit view', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'DSPs', exact: true })).toBeVisible();
  await expect(banner).toHaveCount(0);
  await page.getByRole('button', { name: 'Actions for Atlas Routes', exact: true }).click();
  await page.getByRole('menuitem', { name: 'View', exact: true }).click();
  await expect(banner).toContainText('Viewing Atlas Routes as DSP owner');
  await nav(page).getByRole('link', { name: 'Team & Roles', exact: true }).click();
  await expect(page.getByText('No members found', { exact: true })).toBeVisible();
  await expect(page.getByText('Alex Morgan', { exact: true })).toHaveCount(0);
  await page.getByRole('tab', { name: 'Roles', exact: true }).click();
  await expect(page.locator('.role-row h2')).toHaveText(['Owner', 'Manager', 'Dispatcher', 'Driver']);
  await page.locator('.desktop-sidebar .account-button').click();
  await page.getByRole('menuitem', { name: 'Sign out', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Sign in', exact: true })).toBeVisible();
  expect(await page.evaluate(() => sessionStorage.getItem('dispatch-dsp-view'))).toBeNull();
  expect(errors).toEqual([]);
});

test('mobile DSP view keeps the banner and exit usable', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await login(page);
  await page.getByRole('button', { name: 'Northline Logistics NL01', exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'View', exact: true }).click();
  const banner = page.getByRole('region', { name: 'DSP viewing mode' });
  await expect(banner).toContainText('Northline Logistics');
  await page.getByRole('button', { name: 'Open navigation', exact: true }).click();
  await page.getByRole('dialog').getByRole('link', { name: 'Team & Roles', exact: true }).click();
  await expect(page.getByText('Alex Morgan', { exact: true })).toBeVisible();
  await expect(banner.getByRole('button', { name: 'Exit view', exact: true })).toBeInViewport();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole('tab', { name: 'Roles', exact: true }).click();
  await expect(page.locator('.role-row h2')).toHaveText(['Owner', 'Manager', 'Dispatcher', 'Driver']);
  await expect(page.getByRole('button', { name: 'Create role', exact: true })).toHaveCount(0);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: '/tmp/dispatch-fixed-roles-mobile.png', fullPage: true });
  await page.getByRole('button', { name: 'Invite member', exact: true }).click();
  await expect(page.getByLabel('Role', { exact: true }).locator('option')).toHaveText(['Owner', 'Manager', 'Dispatcher', 'Driver']);
  await page.getByLabel('Role', { exact: true }).selectOption({ label: 'Owner' });
  await expect(page.getByLabel('Role', { exact: true }).locator('option:checked')).toHaveText('Owner');
  await page.getByRole('button', { name: 'Cancel', exact: true }).click();
  await banner.getByRole('button', { name: 'Exit view', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'DSPs', exact: true })).toBeVisible();
});


test('an invalidated view returns to the platform with an explanation', async ({ page }) => {
  await login(page);
  await page.evaluate(() => sessionStorage.setItem('dispatch-dsp-view', 'x'.repeat(43)));
  await page.goto('/#/team');
  await page.reload();
  await expect(page.getByRole('heading', { name: 'DSPs', exact: true })).toBeVisible();
  await expect(page.getByText('The DSP view expired or is no longer available. You’re back in the platform console.')).toBeVisible();
  await expect(page.getByRole('region', { name: 'DSP viewing mode' })).toHaveCount(0);
  expect(await page.evaluate(() => sessionStorage.getItem('dispatch-dsp-view'))).toBeNull();
});
