const {test,expect}=require('@playwright/test');
const {createPreview}=require('../../examples/independent-updates-preview');
let app;
test.beforeAll(async()=>{app=await createPreview({automatic:false});});
test.afterAll(async()=>{await app?.close();});
test('rollout feedback survives preparation, reload, progress, pause, failure and completion',async({page},info)=>{
 test.setTimeout(90000);
 const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',e=>{if(e.type()==='error')errors.push(e.text());});
 await page.goto(`${app.url}/#/updates`);
 await page.getByLabel('Email address').fill('platform@example.test');
 await page.getByLabel('Password',{exact:true}).fill('synthetic preview password');
 await page.getByRole('button',{name:'Sign in',exact:true}).click();
 await page.locator('.desktop-sidebar').getByRole('link',{name:'Updates',exact:true}).click();
 await expect(page.getByRole('heading',{name:'DSP',exact:true})).toBeVisible();
 const response=await page.request.get(`${app.url}/api/platform/updates`);
 const envelope=await response.json(),view=envelope.data;
 view.tracks.dsp.tested=true;view.tracks.dsp.canUpdate=true;view.jobs=[];view.rollout=null;view.operation=null;
 let accept,postCount=0;
 await page.route('**/api/platform/updates',async route=>{
  if(route.request().method()==='POST'){
   postCount++;await new Promise(resolve=>{accept=resolve;});
   await route.fulfill({json:{...envelope,data:view}});
  }else await route.fulfill({json:{...envelope,data:view}});
 });
 await page.reload();
 await expect(page.getByRole('button',{name:'Rollout Update',exact:true})).toBeEnabled();
 await page.getByRole('button',{name:'Rollout Update',exact:true}).click();
 const status=page.getByRole('status').filter({has:page.getByRole('heading')});
 await expect(status).toContainText('Sending rollout…');
 await expect(page.getByRole('button',{name:'Sending request…',exact:true})).toBeDisabled();
 view.jobs=[{id:'progress-job',action:'rollout',product:'dsp',status:'queued',failure:null}];view.busy=true;view.tracks.dsp.canUpdate=false;
 await expect.poll(()=>Boolean(accept)).toBe(true);accept();
 await expect(status).toContainText('Rollout queued');
 view.jobs[0].status='running';
 await expect(status).toContainText('Rollout in progress',{timeout:10000});
 await expect(page.getByRole('button',{name:'Preparing rollout…',exact:true})).toBeDisabled();
 const spinner=status.locator('.motion-safe\\:animate-spin');
 await page.emulateMedia({reducedMotion:'no-preference'});
 await expect.poll(()=>spinner.evaluate(node=>getComputedStyle(node).animationName)).not.toBe('none');
 await page.emulateMedia({reducedMotion:'reduce'});
 await expect.poll(()=>spinner.evaluate(node=>getComputedStyle(node).animationName)).toBe('none');
 await page.screenshot({path:info.outputPath('preparing-desktop.png'),fullPage:true});
 await page.reload();await expect(status).toContainText('Rollout in progress');
 view.worker.available=false;
 await expect(status).toContainText('Waiting for update status',{timeout:10000});
 view.worker.available=true;
 view.jobs[0].status='completed';view.busy=false;
 view.rollout={version:'0.0.2',status:'running',failure:null,updated:0,total:2,members:[{name:'Northline Logistics',status:'updating'},{name:'Cedar Delivery',status:'queued'}]};
 view.operation={product:'dsp',phase:'starting',dspName:'Northline Logistics'};
 await expect(status).toContainText('Updating Northline Logistics',{timeout:10000});
 await expect(status).toContainText('Installing the release and checking service health');
 await expect(page.getByRole('progressbar',{name:'DSPs updated'})).toHaveAttribute('value','0');
 view.operation=null;view.rollout.updated=1;view.rollout.members[0].status='updated';view.rollout.status='paused';
 await expect(status).toContainText('Rollout paused',{timeout:10000});
 await expect(status).toContainText('1 of 2 DSPs updated');
 view.rollout=null;view.jobs[0].status='failed';view.jobs[0].failure='release_runtime_not_ready';
 await expect(status).toContainText('Rollout failed',{timeout:10000});
 await expect(status).toContainText('runtime did not pass');
 view.jobs[0].status='completed';view.jobs[0].failure=null;
 view.rollout={version:'0.0.2',status:'completed',failure:null,updated:2,total:2,members:[{name:'Northline Logistics',status:'updated'},{name:'Cedar Delivery',status:'updated'}]};
 await expect(status).toContainText('Rollout complete',{timeout:10000});
 await expect(status).toContainText('2 of 2 DSPs updated');
 await page.setViewportSize({width:390,height:844});
 await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.screenshot({path:info.outputPath('completed-mobile.png'),fullPage:true});
 await expect(page).toHaveTitle('Updates · Dispatch');expect(postCount).toBe(1);expect(errors).toEqual([]);
});
