'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const {createReleaseDelivery}=require('../server/release-delivery');
const {createPlatformUpdates}=require('../../core/accounts/src/platform-updates');
test('delivery status is sanitized and retry requests are bounded rather than rollout commands',t=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'dispatch-delivery-ui-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));
 fs.mkdirSync(path.join(root,'config'));const file=path.join(root,'config/release-delivery-status.json');
 const delivery=createReleaseDelivery(root);assert.equal(delivery.view(),null);
 assert.throws(()=>delivery.retry());
 fs.writeFileSync(file,JSON.stringify({state:'failed',version:'1.2.3',changelog:[],retryable:true,message:'PRIVATE_PATH_TOKEN'}),{mode:0o600});
 assert.equal(JSON.stringify(delivery.view()).includes('PRIVATE_PATH_TOKEN'),false);
 const updates=createPlatformUpdates({store:{db:{}},enabled:true,delivery});
 updates.command({}, {action:'retry_download'});
 const request=JSON.parse(fs.readFileSync(path.join(root,'config/release-delivery-retry.json')));
 assert.match(request.nonce,/^[a-f0-9]{32}$/);
 assert.throws(()=>updates.command({}, {action:'retry_download',releaseId:'unexpected'}));
 const disabled=createPlatformUpdates({store:{db:{}},enabled:false,delivery});
 assert.throws(()=>disabled.command({}, {action:'retry_download'}));
 fs.chmodSync(file,0o644);assert.equal(delivery.view().retryable,false);
});
